CREATE TABLE user (
	USER_ID BIGINT IDENTITY NOT NULL,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	USER_NAME VARCHAR(255),
	EMAIL_ADDRESS VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	CREATED_DATE TIMESTAMP,
	CREATED_BY VARCHAR(45),
	MODIFIED_DATE TIMESTAMP,
	MODIFIED_BY VARCHAR(45),
	LOCATION VARCHAR(20),
	STATUS INTEGER NOT NULL,
	PRIMARY KEY (USER_ID)
);


INSERT INTO user(USER_ID, FIRST_NAME, LAST_NAME, USER_NAME, EMAIL_ADDRESS, PASSWORD, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, LOCATION, STATUS) VALUES (1, 'MDM', 'Admin', 'admin@up.com', 'admin@up.com', 'prokarma', '2012-09-13 00:00:00', 'SUPER ADMIN', '2012-09-27 23:37:33', 'SUPER ADMIN','Atlanta', 1);
